### ISSUE TITLE
I have problems with the installation of the requirements

### ISSUE THREAD

**Issue by emovtrans** [Ravi-Teja-konda/Surveillance_Video_Summarizer#2]
Hi,

first of all, great jobs!

I want to use your develop but I have a problem when I try to install the requirements.

whats specific version of the library are you using? there are any other requirements? version of CUDA or Torch?

Thank you!

**Comment by bhargavvmukti** [comment]
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
onnx==1.16.2
onnxruntime==1.18.1
torch==2.4.0
torchaudio==2.4.0
torchvision==0.19.0


This versions worked nicely for me . Give it a try !
