### ISSUE TITLE
datasets format for finetuning 

### ISSUE THREAD

**Issue by thunder95** [Ravi-Teja-konda/Surveillance_Video_Summarizer#3]
nice work， sir! how did you generate the question and response in your dataset format? I have noticed you made a custom task prompt with tag "\<SURVEILLANCE\>". would you like to give me an example of that?

**Comment by Ravi-Teja-konda** [comment]
Hey @thunder95 ,
Thank for your interest..

We can create tag for training the model
Below are the colab links you can follow for reference

For finetuning : https://colab.research.google.com/github/merveenoyan/smol-vision/blob/main/Fine_tune_Florence_2.ipynb
For hands on florence - 2 : https://colab.research.google.com/github/merveenoyan/smol-vision/blob/main/Fine_tune_Florence_2.ipynb
